### ISSUE TITLE
Event log was flooded with: Unknown Device type every few seconds

### ISSUE THREAD

**Issue by seemuellera** [Wolbolar/IPSymconEchoRemote#13]
I have a few devices that are not recognized by the plugin, e.g. the FitBit watch of my wife.

The device type is: A2XPGY5LRKB9BE

**If Symcon is restarted every few seconds the following message appears in the log:**
01/28/2020, 9:39:32 PM | AmazonEchoConfigurator | Unknown DeviceType: A2XPGY5LRKB9BE
01/28/2020, 9:39:38 PM | AmazonEchoConfigurator | Unknown DeviceType: A2XPGY5LRKB9BE
01/28/2020, 9:39:47 PM | AmazonEchoConfigurator | Unknown DeviceType: A2XPGY5LRKB9BE
01/28/2020, 9:40:00 PM | AmazonEchoConfigurator | Unknown DeviceType: A2XPGY5LRKB9BE
01/28/2020, 9:42:15 PM | AmazonEchoConfigurator | Unknown DeviceType: A2XPGY5LRKB9BE

I have the feeling that if I configure some instances the log messages stop to appear but I have not found a deterministic behavior yet.

**The expected behavior would be:**
The message is logged once when the plugin is initialized.

**Comment by Wolbolar** [comment]
DeviceType: A2XPGY5LRKB9BE was added.
