### ISSUE TITLE
DEVICETYPE = AKKLQD9FZWWQS --> Jabra Elite 75t

### ISSUE THREAD

**Issue by SmilyHM** [Wolbolar/IPSymconEchoRemote#17]
Hallo zusammen,

habe gesehen, dass der o.g. DEVICETYPE noch nicht enthalten ist. Denke, es wird keine "sinnvolle" Verwendung dafür geben, aber der Vollständigkeit halber, falls gewünscht. Es handelt sich um Blootooth-InEar-Kopfhörer.

Viele Grüße
Sascha

**Comment by Wolbolar** [comment]
Wurde hinzugefügt
