### ISSUE TITLE
Echo Show 8 only partially works

### ISSUE THREAD

**Issue by fuso2001** [Wolbolar/IPSymconEchoRemote#22]
Hi,
the controls for my Echo Show 8 only partially work. The functions such as weather or traffic are running. Play / Pause, Volume etc. show a small window with "Error" in the interface. Nothing happens in the instance.
I've already uninstalled, installed, and relinked everything. The result stays the same.
![image](https://user-images.githubusercontent.com/79335160/111028228-a0076f00-83f5-11eb-89d5-f3375facae2e.png)

This works fine.
![image](https://user-images.githubusercontent.com/79335160/111028334-4d7a8280-83f6-11eb-9d95-188b700f84ab.png)

What can that be? Has Amazon changed anything?

Best regards
Frank

**Comment by Wolbolar** [comment]
Have you tried the newest version of the module in the beta branch? Does the problem still exist with the newest version?

**Comment by fuso2001** [comment]
> Have you tried the newest version of the module in the beta branch? Does the problem still exist with the newest version?

No I did not. After I tried it it worked again.
Thank you very much.
Frank
